config/routes.rb
Rails.application.routes.draw do
  resources :answer_comments
  root to: "comments#index"
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  resources :comments
  resources :products
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/answer_comment.rb
class AnswerComment < ApplicationRecord
    belongs_to :comment
end

app/controllers/answer_comments_controller.rb
class AnswerCommentsController < ApplicationController
  before_action :authorize, only: %i[ index show edit update destroy]
  before_action :set_answer_comment, only: %i[ show edit update destroy ]

  # GET /answer_comments or /answer_comments.json
  def index
    @answer_comments = AnswerComment.all
  end

  # GET /answer_comments/1 or /answer_comments/1.json
  def show
  end

  # GET /answer_comments/new
  def new
    @answer_comment = AnswerComment.new
  end

  # GET /answer_comments/1/edit
  def edit
  end

  # POST /answer_comments or /answer_comments.json
  def create
    @answer_comment = AnswerComment.new(answer_comment_params)

    respond_to do |format|
      if @answer_comment.save
        format.html { redirect_to @answer_comment, notice: "Answer comment was successfully created." }
        format.json { render :show, status: :created, location: @answer_comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @answer_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answer_comments/1 or /answer_comments/1.json
  def update
    respond_to do |format|
      if @answer_comment.update(answer_comment_params)
        format.html { redirect_to @answer_comment, notice: "Answer comment was successfully updated." }
        format.json { render :show, status: :ok, location: @answer_comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @answer_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answer_comments/1 or /answer_comments/1.json
  def destroy
    @answer_comment.destroy
    respond_to do |format|
      format.html { redirect_to answer_comments_url, notice: "Answer comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer_comment
      @answer_comment = AnswerComment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def answer_comment_params
      params.require(:answer_comment).permit(:answer)
    end
end

app/helpers/answer_comments_helper.rb
module AnswerCommentsHelper
end

app/views/answer_comments/_form.html.erb
<%= form_with(model: answer_comment) do |form| %>
  <% if answer_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(answer_comment.errors.count, "error") %> prohibited this answer_comment from being saved:</h2>

      <ul>
        <% answer_comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :answer %>
    <%= form.text_field :answer %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/answer_comments/edit.html.erb
<h1>Editing Answer Comment</h1>

<%= render 'form', answer_comment: @answer_comment %>

<%= link_to 'Show', @answer_comment %> |
<%= link_to 'Back', answer_comments_path %>

app/views/answer_comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Answer Comments</h1>

<table>
  <thead>
    <tr>
      <th>Answer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @answer_comments.each do |answer_comment| %>
      <tr>
        <td><%= answer_comment.answer %></td>
        <td><%= link_to 'Show', answer_comment %></td>
        <td><%= link_to 'Edit', edit_answer_comment_path(answer_comment) %></td>
        <td><%= link_to 'Destroy', answer_comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Answer Comment', new_answer_comment_path %>

app/views/answer_comments/new.html.erb
<h1>New Answer Comment</h1>

<%= render 'form', answer_comment: @answer_comment %>

<%= link_to 'Back', answer_comments_path %>

app/views/answer_comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Answer:</strong>
  <%= @answer_comment.answer %>
</p>

<%= link_to 'Edit', edit_answer_comment_path(@answer_comment) %> |
<%= link_to 'Back', answer_comments_path %>